---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: "%d7%a0%d7%99%d7%a6%d7%97%d7%a0%d7%95-%d7%91%d7%93%d7%a8%d7%9a-%d7%9c%d7%9e%d7%a2%d7%91%d7%a8-%d7%91%d7%98%d7%95%d7%97.md"
  label: TestPage
  match: "**/*"
- type: document
  path: README.md
  label: Home
- type: directory
  path: lessons
  label: Posts
  create: documents
  match: "**/*"
upload_dir: ".vuepress/public/images/uploads"
public_path: images//uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
